# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iprecord',
            options={'ordering': ('-create_time',), 'verbose_name': '访问者IP历史记录'},
        ),
    ]
