# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-22 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-create_time',), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
