# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='默认', max_length=255, unique=True, verbose_name='名称'),
        ),
    ]
