# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20161113_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='key_word',
            new_name='keyword',
        ),
    ]
