# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20161114_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='keyword',
            field=models.ManyToManyField(blank=True, null=True, to='cms.KeyWord'),
        ),
    ]
