# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20161114_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.Category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='content',
            name='keyword',
            field=models.ManyToManyField(to='cms.KeyWord', verbose_name='关键字'),
        ),
    ]
