# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20161114_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'permissions': (('write', '写文章'),), 'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
    ]
