# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0011_auto_20161120_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='喜欢数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='cms.Category', verbose_name='类别')),
                ('keyword', models.ManyToManyField(to='cms.KeyWord', verbose_name='关键字')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章',
                'permissions': (('write', '写文章'),),
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reply', models.PositiveIntegerField(default=None, help_text='这里是回复的评论的ID', verbose_name='回复评论id')),
                ('content', models.TextField(verbose_name='内容')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('is_article', models.BooleanField(help_text='是文章下面的留言，或者是留言板的留言', verbose_name='是否文章留言')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.RemoveField(
            model_name='content',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
