# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20161129_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like',
            new_name='like_times',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='visit_count',
            new_name='visit_times',
        ),
        migrations.RemoveField(
            model_name='article',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(default='', max_length=255, verbose_name='关键字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'article'), (2, 'board')], default=1, verbose_name='留言的类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
    ]
