# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20170804_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-create_time',), 'permissions': (('write', '写文章'),), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
